import Footer from '@/components/footer/Footer'
import NavBar from '@/components/navbar/NavBar'
import '@/app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen bg-white ${inter.className}`}
      >
        <div className="flex-1">
          <NavBar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
